steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/smartfile-422907/smartfile_dev", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/smartfile-422907/smartfile_dev"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          [
              "run",
              "deploy",
              "smartfile-dev",
              "--image",
              "gcr.io/smartfile-422907/smartfile_dev",
              "--region",
              "us-central1",
          ]
images:
    - gcr.io/smartfile-422907/smartfile_dev
