version: '3'
services:
  smartfile-chat-app:
    image: smartfile-chat-app:latest
    build: /cloud
    command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
    - ./:/app
    ports:
    - 8080:8080