services:
  smartfile-chat-app:
    image: gcr.io/smartfile-422907/smartfile-docker/server-image:latest
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
    - ./:/app
    ports:
    - 8080:8080